[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nclsbayona"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/nclsbayona"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "feeds"
name = "RSS Feeds"
url = "https://nclsbayona.github.io/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "github"
name = "Github"
url = "https://www.github.com/nclsbayona"

[social.params]
icon = "brand-github"