name: Update theme

# Controls when the workflow will run
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/update-theme.yml'
  schedule:
    # Update theme automatically everyday at 01:00 UTC
    - cron: "0 1 * * *"

jobs:
  update-theme:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - uses: actions/checkout@v6
        with:
            persist-credentials: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Update theme
        run: hugo mod get -u github.com/CaiJimmy/hugo-theme-stack/v3

      - name: Tidy go.mod, go.sum
        run: hugo mod tidy

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: :arrow_up: Update theme"
